config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :transactions
  resources :categories

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations'
  }

  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :user
  belongs_to :categorizable, polymorphic: true
  has_many :sub_categories, as: :categorizable, dependent: :destroy,
                            inverse_of: :categorizable, class_name: 'Category'

  has_many :transactions, dependent: :destroy

  validates :name, length: {in: 1..80}
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  extend Enumerize

  KIND_TYPES = %i[income expense open_transfer category_transfer].freeze

  enumerize :kind, in: KIND_TYPES

  belongs_to :category, optional: true
  belongs_to :origin, class_name: 'Category', optional: true, inverse_of: :transactions
  belongs_to :user

  monetize :amount_cents

  validates :amount, numericality: {
    greater_than_or_equal_to: 0.01
  }
  validates :comment, length: {maximum: 80}
  validates :user, presence: true
  validates :date, presence: true
  validates :kind, presence: true, inclusion: {in: KIND_TYPES.map(&:to_s)}

  scope :last_ten, -> { order(id: :desc).limit(10) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :confirmable, :omniauthable,
    omniauth_providers: %i[google github]

  validates :name, presence: true

  validates_integrity_of  :avatar
  validates_processing_of :avatar

  has_many :transactions, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :sub_categories, as: :categorizable, dependent: :destroy,
                            inverse_of: :categorizable, class_name: 'Category'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :set_locale

  def after_sign_in_path_for(_resource)
    request.env['omniauth.origin'] || root_path
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:error] = I18n.t('not_authorized')
    redirect_to(request.referer || root_path)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[edit update destroy]
  before_action :set_parent, only: %i[new create]

  def index
    @categories = Category.where(user: current_user).order(:name)
    @transactions = current_user.transactions.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @category = @parent.sub_categories.new
    render :form
  end

  def edit
    render :form
  end

  def create
    @category = CreateCategoryService.new(parent: @parent, params: category_params).call

    if @category.persisted?
      redirect_back fallback_location: root_path,
                    notice: I18n.t('categories.category_created')
    else
      render :form
    end
  end

  def update
    if @category.update(category_params)
      redirect_back fallback_location: root_path,
                    notice: I18n.t('categories.category_updated')
    else
      render :form
    end
  end

  def destroy
    @category.destroy
    redirect_back fallback_location: root_path,
                  notice: I18n.t('categories.category_destroyed')
  end

  private

  def set_parent
    @parent ||= current_category || current_user
  end

  def set_category
    @category = Category.find(params[:id])
    authorize @category
  end

  def current_category
    category_id = params[:category_id]
    current_user.categories.find_by(id: category_id) if category_id.present?
  end

  def category_params
    params.require(:category).permit(:name).merge(user: current_user)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :require_login, only: :index

  def index
    current_user_transactions = current_user.transactions
    @transaction = current_user_transactions.new(kind: 'income')
    @transactions = current_user_transactions.last_ten
  end

  private

  def require_login
    render :landing if current_user.blank?
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[edit update destroy]

  def index
    @search_query = current_user.transactions.order(created_at: :desc).ransack(params[:q])
    @transactions = @search_query.result.page(params[:page]).per(5)
  end

  def new
    @transaction = current_user.transactions.new(
      category_id: params[:category_id],
      kind: params[:kind] || 'income'
    )
    render :form
  end

  def edit
    render :form
  end

  def create
    @transaction = current_user.transactions.new(transaction_params)

    if @transaction.save
      redirect_back fallback_location: root_path,
                    notice: I18n.t('transactions.transaction_created')
    else
      render :form
    end
  end

  def update
    if @transaction.update(transaction_params)
      redirect_back fallback_location: root_path,
                    notice: I18n.t('transactions.transaction_updated')
    else
      render :form
    end
  end

  def destroy
    @transaction.destroy
    redirect_back fallback_location: root_path,
                  notice: I18n.t('transactions.transaction_destroyed')
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
    authorize @transaction
  end

  def transaction_params
    params.require(:transaction)
      .permit(:amount, :comment, :date, :kind, :category_id)
      .merge(kind: @transaction&.kind || params[:kind] || params[:transaction][:kind])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  protected

  # The path used after confirmation.
  def after_confirmation_path_for(_resource_name, resource)
    sign_in(resource)
    root_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    handle_oauth
  end

  def github
    handle_oauth
  end

  private

  def user
    @user ||= OauthService.new(request.env['omniauth.auth']).process_user
  end

  def handle_oauth
    sign_in_and_redirect user
  rescue ActiveRecord::RecordInvalid
    redirect_when_duplicate_email
  end

  def redirect_when_duplicate_email
    redirect_to new_user_session_path, flash: {
      error: I18n.t('errors.redirect_when_duplicate_email')
    }
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :authorize_account_edit, only: %i[edit update]

  def create
    super
    CreateStandardCategoriesService.new(user: resource).call
  end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys:
      %i[name avatar avatar_cache remove_avatar])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys:
      %i[name avatar avatar_cache remove_avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def oauth_provider_humanized
    case provider
    when 'google' then 'Google'
    when 'github' then 'GitHub'
    end
  end

  delegate :provider, to: :current_user

  def authorize_account_edit
    reject_oauth_editing if provider
  end

  def reject_oauth_editing
    redirect_to root_path, flash: {
      error: I18n.t('errors.edit_oauth_profile', provider:
        oauth_provider_humanized)
    }
  end
end

app/views/categories/form.js.slim
| $("#modal-window").html("#{escape_javascript(cell(:categories, @category).(:modal))}");
| $('#modal-window').modal('show');

app/views/categories/index.html.slim
h3.text-center
  = I18n.t('categories.all_categories')
= link_to(new_category_path, remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window') do
  i.fa.fa-plus-circle[aria-hidden="true"]
  '
  = I18n.t('categories.new_category')
= cell(:categories).(:list, @categories)

- if @transactions.empty?
  h4.text-center
    = I18n.t('transactions.no_transactions')
- else
  h3.text-center
    = I18n.t('transactions.all_transactions')
  = cell(:transactions).(:list, @transactions)
= paginate @transactions

app/views/home/index.html.slim
p.text-center
  = I18n.t('home.index.welcome_back', name: current_user.name)
  div#home_new_transaction_form
    = cell(:transactions, @transaction).(:form, controller_name)
hr
h3.text-center
  = I18n.t('transactions.your_last_transactions', quantity: @transactions.count)
= cell(:transactions).(:list, @transactions)

app/views/home/landing.html.slim
p.text-center
  = I18n.t('home.index.please_log_in')

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = I18n.t('title')
    = csrf_meta_tags

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'stylesheets'

    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
  body
    = cell(:navbar).()
    .container
      = cell(:flash).()
      .card
        .card-body
          = yield

  #modal-window.modal[tabindex="-1" role="dialog"].hide.fade[role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"]

app/views/shared/_flash_messages.html.slim
#flash_messages
  - flash.each do |key, value|
    = content_tag(:div, value, class: flash_class(key.to_sym), role: 'alert')

app/views/transactions/form.js.slim
- if params[:controller_name] == 'home'
  | $("#home_new_transaction_form").html("#{escape_javascript(cell(:transactions, @transaction).(:form, 'home'))}");
- else
  | $("#modal-window").html("#{escape_javascript(cell(:transactions, @transaction).(:modal))}");
  | $('#modal-window').modal('show');

app/views/transactions/index.html.slim
h3.text-center
  = I18n.t('transactions.all_transactions')
= cell(:transactions).(:search_form, @search_query)
hr
= link_to(new_transaction_path, remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window') do
  i.fa.fa-plus-circle[aria-hidden="true"]
  '
  = I18n.t('transactions.add_transaction')
br
= link_to(new_category_path, remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window') do
  i.fa.fa-plus-circle[aria-hidden="true"]
  '
  = I18n.t('categories.new_category')

- if @transactions.empty?
  h4.text-center
    = I18n.t('transactions.no_transactions')
- else
  = cell(:transactions).(:list, @transactions)
= paginate @transactions